[package]
edition = "2021"
name = "publisher"
version = "1.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
ic-cdk-macros = "0.8"
serde = "1.0"
serde_derive = "1.0"
